### ISSUE TITLE
Can't find your microphone popup

### ISSUE THREAD

**Issue by govindms777** [bunnykek/BonkMeet#1]
When trying to join a meet a popup that says can't find your microphone comes up. The bot gets stuck on this screen and does not join. Since it hasn't actually joined the /leave command does not work either. It says that i am not attending any gmeet session. Please fix this as this is a very helpful bot. Thank you.

**Comment by bunnykek** [comment]
Oh thanks. I redeployed the bot and i am also facing this issue. I will fix it ASAP

**Comment by bunnykek** [comment]
So now I have fixed that issue, follow these steps to update the bot.
1. Fork the repo.
2. Go to your application's deploy tab in heroku.
3. Select the deployment method as Github.
4. Then connect the forked repo.
5. Then on manual deploy section, deploy the main branch.
Thats all.
